version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy_practice
hooks:
  BeforeInstall:
    - location: scripts/initialize.sh
  AfterInstall:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start.sh
  ApplicationStop:
    - location: scripts/stop.sh
