version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy_practice
hooks:
  AfterInstall:
    - location: scripts/initialize.sh
  ApplicationStart:
    - location: scripts/start.sh
